spring.application.name=demo
# Define el nombre de la aplicación Spring Boot.
# Sirve para identificar el proyecto internamente.

# Datos de conexión
spring.mail.host=smtp.gmail.com
# Define el servidor SMTP que se usará para enviar correos.
# En este caso se usa el servidor de Gmail.

spring.mail.port=587
# Define el puerto de conexión.
# El 587 se usa para SMTP con cifrado TLS.

spring.mail.username=gabrielemanuel.hdz@gmail.com

# Aqui van las 16 letras que google me proporciono, deben ir sin espacios
spring.mail.password=dkkkyogfuthwowod
# Permite que Java envie correos

# Protocolos de seguridad
spring.mail.properties.mail.smtp.auth=true
# Activa la autenticación.
# Le dice al servidor que se enviará usuario y contraseña.

spring.mail.properties.mail.smtp.starttls.enable=true
# Activa el cifrado TLS.
# Sirve para que la conexión sea segura y protegida.